### ISSUE TITLE
[swc-angular-plugin] Issue with Dexie package

### ISSUE THREAD

**Issue by kroeder** [jscutlery/devkit#325]
Hey,

we currently switch from jest (ts-jest) to swc-angular and encountered a few issues.

One of them being that the "Dexie" package cannot be used anymore

```
(0 , _dexie.liveQuery) is not a function
TypeError: (0 , _dexie.liveQuery) is not a function
``` 

I assumed this is related to cjs vs mjs but whatever I tried with moduleNameMapper, ignoreTransformPattern and everything else I usually do if I enocunter these errors, nothing helped.

So this might either be a bug in `swc-angular-plugin` or something I'm doing wrong? 
It's at least a "regression" since it has worked before and does not now by only following the installation instructions in this package.

## Reproduction

https://github.com/kroeder/jest-angular-swc-dexie-reproduction

1) clone package
2) `npm install`
3) `nx test`
4) Test in https://github.com/kroeder/jest-angular-swc-dexie-reproduction/blob/main/src/app/failing-test.spec.ts should fail

**Comment by edbzn** [comment]
Hi @kroeder, sorry for the late reply, I missed the notification.

It seems to be an issue with SWC handling default imports along with destructured imports because in the `failing-test.spec.ts` if you replace: 

```ts
import Dexie, { liveQuery } from 'dexie';
```

with: 

```ts
import { Dexie, liveQuery } from 'dexie';
```

or: 

```ts
import Dexie from 'dexie';

const { liveQuery } = Dexie;
```

then it passes:

![image](https://github.com/jscutlery/devkit/assets/8522558/4d8c7364-9e9e-427c-88c7-35cbd9eec8cc)

I played a bit with the SWC configuration and it turns out that if you set the [noInterop flag](https://swc.rs/docs/configuration/modules#nointerop):

```js
transform: {
  '^.+\\.(ts|mjs|js)$': ['@swc/jest', {
    module: {
      noInterop: true
    },
    // ...
  }],
}
```

the `failing-test.spec.ts` is passing but the rest is failing: 

![image](https://github.com/jscutlery/devkit/assets/8522558/4974a26c-b324-47a7-a629-b0a9a98c5aa4)

**Comment by kroeder** [comment]
This solved it for us, thanks a lot!
